baseurl                 = "/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
defaultContentLanguage  = "en"
isMultilingual          = false
title                   = "Welcome to Project Psyche!"
theme                   = "hello"